name: wish_swish
description: Test task.
publish_to: 'none'
version: 0.0.1-alpha

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # local
  auth_repo:
    path: packages/auth_repo
  category_repo:
    path: packages/category_repo
  order_repo:
    path: packages/order_repo
  product_repo:
    path: packages/product_repo

  # third party
  bloc: ^8.0.3
  connectivity_plus: ^2.3.5
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
