name: order_repo
description: Order Repository.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  product_repo:
    path: ../product_repo

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
